### Joshua Lim - ML HW01
### 1a)
Suppose point $X$, where $X \in \mathbb{R}^n$ is a point satisfying $\theta⋅X+\theta_0=0$. Let the vector $y - X$ be $\lambda$. Then the distance from point $y$ to the hyperplane would be the projection of vector $\lambda$ onto the normal unit vector $\hat{\theta}$. 

\begin{align*}
  &\hat{\theta} = \displaystyle \frac{\theta}{||\theta||}\\
  &d = |\hat{\theta}⋅\lambda|\\
  &d = \displaystyle \frac{\theta⋅(y - X)}{||\theta||}\\
  &Since\; \theta⋅X=−\theta_0,\\
  &d = \displaystyle \frac{\theta⋅y + \theta_0}{||\theta||}
\end{align*}
### 1b)
\begin{align*}
  P(Z =k) &= P(X+ Y =k)\\
    &= \sum_{i=0}^k P(X = k-i , Y =i)\\
    &= \sum_{i=0}^k P(X = k-i)P(Y=i)\\
    &= \sum_{i=0}^k e^{-\alpha}\frac{\alpha^{k-i}}{(k-i)!}e^{-\beta}\frac{\beta^i}{i!}\\
   &= e^{-(\alpha + \beta)}\frac 1{k!}\sum_{i=0}^k \frac{k!}{i!(k-i)!}\alpha^{k-i}\beta^i\\
   &= e^{-(\alpha + \beta)}\frac 1{k!}\sum_{i=0}^k \binom ki\alpha^{k-i}\beta^i\\
   &= \frac{(\alpha + \beta)^k}{k!} \cdot e^{-(\alpha + \beta)}\\
   \\
   where\;\gamma &= \alpha + \beta
\end{align*}


In [6]:
# Qn 2A
import sys
print (sys.version)

import theano
print (theano.__version__)

print("The python version is 3.6.1")
print("The theano version is 0.9.0")

3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
0.9.0.dev-c697eeab84e5b8a74908da654b66ec9eca4f1291
The python version is 3.6.1
The theano version is 0.9.0


In [2]:
# Qn 3A
import numpy as np
import theano
import theano.tensor as T

csv='https://www.dropbox.com/s/oqoyy9p849ewzt2/linear.csv?dl=1'
data = np.genfromtxt(csv,delimiter =',')
X=data[:,1:]
Y=data[:,0]

d=X.shape[1]#dimension of feature vectors
n=X.shape[0]#number of training samples
learn_rate=0.5#learning rate for gradient descent

x=T.matrix(name='x')#feature matrix
y=T.vector(name='y')#response vector
w=theano.shared(np.zeros((d,1)),name='w')#model parameters

risk=T.sum((T.dot(x,w).T-y)**2)/2/n#empiricalrisk
grad_risk=T.grad(risk,wrt=w)#gradientoftherisk
train_model=theano.function(inputs=[],
                            outputs=risk,
                            updates=[(w,w-learn_rate*grad_risk)],
                            givens={x:X, y:Y})

n_steps=50
for i in range(n_steps):
    train_model()
print(np.ravel(w.get_value()))

[-0.57392068  1.35757059  0.01527565 -1.88288076]


In [3]:
# Qn 3B
import numpy as np

csv='https://www.dropbox.com/s/oqoyy9p849ewzt2/linear.csv?dl=1'
data = np.genfromtxt(csv,delimiter =',')
X=data[:,1:]
Y=data[:,0]

#theta = inv(X_trans*X)*X_trans*Y
X_trans = np.transpose(X)
inv = np.linalg.inv(np.dot(X_trans,X))
X_ = np.dot(inv,X_trans)
theta = np.dot(X_,Y)
print (theta)

[-0.57392068  1.35757059  0.01527565 -1.88288076]


In [1]:
# Qn 3C
import numpy as np
csv='https://www.dropbox.com/s/oqoyy9p849ewzt2/linear.csv?dl=1'
data = np.genfromtxt(csv,delimiter =',')
X=data[:,1:]
Y=data[:,0]

print (np.linalg.lstsq(X,Y)[0])

[-0.57392068  1.35757059  0.01527565 -1.88288076]
